#!/usr/bin/python
#
# run all tests
#

import os
import os.path
import sys

os.system("echo HOSTNAME: `hostname`")
os.system("make sequenceTest")

test = "sequenceTest"
processors = [1,2,4,8,16,32]
lengths = [10000000,20000000,40000000,80000000]

try :
      for l in lengths :
        for p in processors :
          ss = "./runtest "+test+" "+`l`+" "+`p`
          os.system("echo")
          os.system("echo "+ss)
          x = os.system(ss)
          if (x) :
            raise NameError("  " + ss)
except NameError :
  print "TEST TERMINATED"
