#!/bin/sh

if test "$OPENMP"
then
export OMP_NUM_THREADS=$3
./$1 $2 
elif test "$GCILK"
then
export CILK_NWORKERS=$3
./$1 $2
elif test "$CILK"
then
./$1 $2 -cilk_set_worker_count $3
elif test "$IPPROOT"
then
export CILK_NWORKERS=$3
./$1 $2
else
./$1 $2
fi
